version: '3'
services:
  consul-server:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    volumes:
      - ./consul-config:/consul/config
    networks:
      - microservices

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./consul.rules.yml:/etc/prometheus/consul.rules.yml
    depends_on:
      - consul-server
    networks:
      - microservices

  consul-exporter:
    image: prom/consul-exporter
    ports:
      - "9107:9107"
    command: --consul.server=consul-server:8500
    depends_on:
      - consul-server
    networks:
      - microservices

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-values.yaml:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    networks:
      - microservices
      
  gateway:
    build:
      context: ./apps/gateway  # Diretório onde está o Dockerfile da sua aplicação
    ports:
      - "8080:8080"  # Mapeia a porta do contêiner para a porta do host
    depends_on:
      - consul-server
    networks:
      - microservices
      
  userservice:
    build:
      context: ./apps/userservice  # Diretório onde está o Dockerfile da sua aplicação
    ports:
      - "3002:3002"  # Mapeia a porta do contêiner para a porta do host
    depends_on:
      - consul-server
    networks:
      - microservices
      
  userservice2:
    build:
      context: ./apps/userservice2  # Diretório onde está o Dockerfile da sua aplicação
    ports:
      - "3003:3003"  # Mapeia a porta do contêiner para a porta do host
    depends_on:
      - consul-server
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
