version: '3'
services:
  consul-server:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    volumes:
      - ./consul-config:/consul/config

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - consul-server

  consul-exporter:
    image: prom/consul-exporter
    ports:
      - "9107:9107"
    command: --consul.server=consul-server:8500
    depends_on:
      - consul-server

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-values.yaml:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
