version: '3'
services:
  consul-server:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    volumes:
      - ./configs:/consul/config
    networks:
      - microservices

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/consul.rules.yml:/etc/prometheus/consul.rules.yml
    depends_on:
      - consul-server
    networks:
      - microservices

  consul-exporter:
    image: prom/consul-exporter
    ports:
      - "9107:9107"
    command: --consul.server=consul-server:8500
    depends_on:
      - consul-server
    networks:
      - microservices

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana-values.yaml:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    networks:
      - microservices
      
  gateway:
    build:
      context: ./apps/gateway
    ports:
      - "8080:8080"
    depends_on:
      - consul-server
    networks:
      - microservices
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices
      
  # ------ Apps ------
      
  userservice:
    build:
      context: ./apps/userservice
    ports:
      - "3002:3002"
    depends_on:
      - consul-server
    networks:
      - microservices
      
  userservice2:
    build:
      context: ./apps/userservice2
    ports:
      - "3003:3003"
    depends_on:
      - consul-server
    networks:
      - microservices
      
  dept:
    build:
      context: ./apps/department
    ports:
      - "3005:3005"
    depends_on:
      - consul-server
    networks:
      - microservices    

  python-consul:
    build:
      context: ./apps/python-consul
    ports:
      - "8585:8585"
    depends_on:
      - consul-server
    networks:
      - microservices   

  node-sendmail:
    build:
      context: ./apps/node-sendmail
    ports:
      - "3001:3001"
    depends_on:
      - consul-server
    networks:
      - microservices      
      
  send-message:
    build:
      context: ./apps/send-message
    ports:
      - "3006:3006"
    depends_on:
      - rabbitmq
    networks:
      - microservices
      
  read-message:
    build:
      context: ./apps/read-message
    ports:
      - "3007:3007"
    depends_on:
      - send-message
    networks:
      - microservices

  read-message2:
    build:
      context: ./apps/read-message2
    ports:
      - "3008:3008"
    depends_on:
      - send-message
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
