# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

adminPassword: password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: 192.168.1.153:9090
      access: proxy
      isDefault: true