global:
  scrape_interval: 15s
  
rule_files:
    - 'consul.rules.yml'
  
scrape_configs:
  - job_name: consul
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets:
          - 192.168.1.153:9107
          
  - job_name: 'apps'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.1.153:8080']
        labels:
          group: 'production'
